name: Lint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: prepare to install
      run: sudo apt-get update
    - name: python for cpplint
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: cppcheck
      run: |
        sudo apt-get install -y cppcheck
        cppcheck --enable=all --std=c++17 --error-exitcode=1 --suppressions-list=.cppcheck_suppressions --xml --xml-version=2 --output-file=cppcheck_results.xml .
      continue-on-error: true

    - name: cpplint
      run: |
        pip install cpplint
        cpplint  --filter=-legal,-build/c++17 --linelength=100 *.cpp *.h
      continue-on-error: true

    - name: clang-format
      run: |
        sudo apt-get install -y clang-tidy
        find . -name "*.cpp" -o -name "*.hpp" -o -name "*.cc" -o -name "*.h" | grep -v "build/" | xargs -I{} clang-tidy {} -- -std=c++17
